version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ksure-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: web_ksure
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # โหลดไฟล์ SQL จากโฟลเดอร์ mysql-init อัตโนมัติ
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
